"""The nested cross-validation driver: search inside, score once outside.

This is the file where the honesty of every reported number is decided, so the
control flow is worth stating precisely.

For each property, and independently within each of the five outer folds:

1. An Optuna study proposes a configuration.
2. That configuration is fitted on each of the three inner folds and scored by the
   mean. Only inner data is touched.
3. Steps 1-2 repeat for T trials, with unpromising ones pruned early.
4. The winning configuration is refitted on the whole outer-training set.
5. That model is scored **once** on the outer test fold.

The estimate is the mean of the five outer scores. Three things about this are easy
to get wrong and are handled explicitly here.

**One study per (outer fold, property).** Fifteen independent studies, not one.
They may select different winners, and that is not a defect to be smoothed over -
it is what keeps the outer estimate unbiased. Sharing a study across folds would
let a configuration chosen with fold 3's data be scored on fold 3's test set.

**The refit cannot use early stopping.** Early stopping needs a validation set, and
the only data left is the outer test fold. Using it would leak. Instead the tree
count is taken from what early stopping settled on during the inner folds - the
mean of the three ``best_iteration`` values - and the refit builds exactly that
many trees with no validation set at all.

**Normalization uses training-fold spread.** RMSE is divided by the standard
deviation of the property over the *training* rows of whichever split is being
scored. Using the test rows' own spread would make the metric depend on how
heterogeneous that fold happened to be, and would leak its scale.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import numpy.typing as npt
import optuna
import polars as pl

from dupont_qspr.config import Config
from dupont_qspr.contracts import PROPERTIES, PROPERTY_UNITS, PropertyName
from dupont_qspr.dataset import Prepared
from dupont_qspr.metrics import point_metrics
from dupont_qspr.metrics.point import rmse
from dupont_qspr.models.xgb import XGBPropertyModel
from dupont_qspr.tracking import RunLogger
from dupont_qspr.tuning.spaces import XGB_SPACE, suggest_xgb

__all__ = ["NestedResult", "OuterFoldResult", "run_nested_xgb"]

optuna.logging.set_verbosity(optuna.logging.WARNING)


@dataclass(slots=True)
class OuterFoldResult:
    """One (property, outer fold) cell of the nested run."""

    property: PropertyName
    fold: int
    best_params: dict[str, Any]
    best_inner_score: float
    n_estimators_refit: int
    n_trials: int
    n_pruned: int
    n_train: int
    n_test: int
    metrics: dict[str, Any]
    seconds: float
    trials: list[dict[str, Any]] = field(default_factory=list)
    #: Out-of-fold predictions on this cell's held-out rows. Concatenated across
    #: folds these cover every labelled molecule exactly once, which is what the
    #: reporting layer plots and what the conformal layer calibrates against.
    test_rows: npt.NDArray[np.int64] = field(
        default_factory=lambda: np.empty(0, np.int64)
    )
    y_true: npt.NDArray[np.float64] = field(default_factory=lambda: np.empty(0))
    y_pred: npt.NDArray[np.float64] = field(default_factory=lambda: np.empty(0))


@dataclass(slots=True)
class NestedResult:
    feature_name: str
    featurizer_version: str
    results: list[OuterFoldResult]
    seconds: float

    def by_property(self) -> dict[str, list[OuterFoldResult]]:
        out: dict[str, list[OuterFoldResult]] = {}
        for entry in self.results:
            out.setdefault(entry.property, []).append(entry)
        return out

    def predictions_frame(self, smiles: list[str]) -> pl.DataFrame:
        """Every out-of-fold prediction, one row per (molecule, property).

        Because each molecule sits in exactly one outer test fold, concatenating
        the cells gives a prediction for every labelled molecule made by a model
        that never trained on it. That is simultaneously what the scatter plots
        need and what conformal calibration will need at step 8, so it is written
        once here rather than regenerated by re-running anything.
        """
        frames = [
            pl.DataFrame(
                {
                    "property": [r.property] * r.test_rows.size,
                    "fold": np.full(r.test_rows.size, r.fold, dtype=np.int64),
                    "row_index": r.test_rows,
                    "smiles": [smiles[i] for i in r.test_rows],
                    "y_true": r.y_true,
                    "y_pred": r.y_pred,
                }
            )
            for r in self.results
            if r.test_rows.size
        ]
        return pl.concat(frames, how="vertical") if frames else pl.DataFrame()

    def estimate(self) -> dict[str, dict[str, Any]]:
        """Mean and spread across outer folds, per property, per metric.

        The spread is reported rather than hidden. With five folds and one of them
        dominated by a single 6,137-molecule scaffold group, a wide interval is
        information about the split, not an embarrassment.
        """
        summary: dict[str, dict[str, Any]] = {}
        for prop, entries in self.by_property().items():
            collected: dict[str, list[float]] = {}
            for entry in entries:
                for key, value in entry.metrics.items():
                    if (
                        key != "n"
                        and isinstance(value, (int, float))
                        and np.isfinite(value)
                    ):
                        collected.setdefault(key, []).append(float(value))
            summary[prop] = {
                "units": PROPERTY_UNITS[prop],  # type: ignore[index]
                "n_folds": len(entries),
                "n_test_total": sum(e.metrics.get("n", 0) for e in entries),
                **{
                    key: {
                        "mean": float(np.mean(values)),
                        "std": float(np.std(values, ddof=1))
                        if len(values) > 1
                        else 0.0,
                        "per_fold": [round(v, 4) for v in values],
                    }
                    for key, values in collected.items()
                },
            }
        return summary


def _study_seed(base: int, prop: PropertyName, fold: int) -> int:
    """Deterministic but distinct per (property, fold), so studies are independent."""
    return (base + 1000 * (PROPERTIES.index(prop) + 1) + 17 * fold) % (2**31 - 1)


def _run_one_cell(
    data: Prepared,
    cfg: Config,
    prop: PropertyName,
    prop_index: int,
    fold: int,
    logger: RunLogger,
) -> OuterFoldResult:
    started = time.perf_counter()
    outer = data.folds.outer[fold]
    inner_splits = data.folds.inner[fold]

    trials: list[dict[str, Any]] = []

    def objective(trial: optuna.Trial) -> float:
        params = suggest_xgb(trial)
        scores: list[float] = []
        iterations: list[int] = []

        for step, split in enumerate(inner_splits):
            train_rows = data.labelled(split.train_idx, prop_index)
            test_rows = data.labelled(split.test_idx, prop_index)
            if train_rows.size < 10 or test_rows.size < 3:
                continue

            model = XGBPropertyModel(
                params=params,
                n_jobs=cfg.models.xgb_n_jobs,
                max_rounds=cfg.models.xgb_max_rounds,
                early_stopping_rounds=cfg.models.xgb_early_stopping_rounds,
                seed=cfg.seed,
            ).fit(
                data.X[train_rows],
                data.Y[train_rows, prop_index],
                eval_set=(data.X[test_rows], data.Y[test_rows, prop_index]),
            )
            predicted = model.predict(data.X[test_rows])
            spread = data.train_sd(split.train_idx, prop_index)
            scores.append(rmse(data.Y[test_rows, prop_index], predicted) / spread)
            iterations.append(model.best_iteration or cfg.models.xgb_max_rounds)

            # Pruning needs a running estimate after each inner fold. A clearly
            # bad configuration is abandoned after one or two fits instead of three.
            trial.report(float(np.mean(scores)), step)
            if trial.should_prune():
                raise optuna.TrialPruned

        if not scores:
            raise optuna.TrialPruned

        mean_score = float(np.mean(scores))
        # Carried on the trial so the winner's tree count is available for the
        # refit without re-running anything.
        trial.set_user_attr("n_estimators", int(np.mean(iterations)))
        trial.set_user_attr("inner_scores", [round(s, 5) for s in scores])
        trials.append(
            {
                "number": trial.number,
                "params": params,
                "inner_scores": [round(s, 5) for s in scores],
                "mean": round(mean_score, 5),
                "n_estimators": int(np.mean(iterations)),
            }
        )
        return mean_score

    study = optuna.create_study(
        direction="minimize",
        sampler=optuna.samplers.TPESampler(seed=_study_seed(cfg.seed, prop, fold)),
        pruner=(
            # n_warmup_steps=0 prunes after the first inner fold rather than the second,
            # which is where most of the saving is: a hopeless configuration costs
            # one fit instead of three.
            optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=0)
            if cfg.tuning.pruning
            else optuna.pruners.NopPruner()
        ),
    )
    study.optimize(
        objective,
        n_trials=cfg.tuning.n_trials,
        timeout=cfg.tuning.timeout_s,
        catch=(),
    )

    best = study.best_trial
    n_estimators = int(best.user_attrs.get("n_estimators", cfg.models.xgb_max_rounds))

    # Refit on the entire outer-training set with a FIXED tree count. No eval_set:
    # the only untouched data is the outer test fold and using it would leak.
    train_rows = data.labelled(outer.train_idx, prop_index)
    test_rows = data.labelled(outer.test_idx, prop_index)
    final = XGBPropertyModel(
        params=best.params,
        n_jobs=cfg.models.xgb_n_jobs,
        seed=cfg.seed,
    ).fit(
        data.X[train_rows],
        data.Y[train_rows, prop_index],
        n_estimators=n_estimators,
    )

    # The single evaluation on held-out data, after every choice has been made.
    predicted = final.predict(data.X[test_rows])
    metrics = point_metrics(
        data.Y[test_rows, prop_index],
        predicted,
        train_sd=data.train_sd(outer.train_idx, prop_index),
    )

    n_pruned = sum(1 for t in study.trials if t.state == optuna.trial.TrialState.PRUNED)
    result = OuterFoldResult(
        property=prop,
        fold=fold,
        best_params=dict(best.params),
        best_inner_score=float(best.value),
        n_estimators_refit=n_estimators,
        n_trials=len(study.trials),
        n_pruned=n_pruned,
        n_train=int(train_rows.size),
        n_test=int(test_rows.size),
        metrics=metrics,
        seconds=time.perf_counter() - started,
        trials=trials,
        test_rows=test_rows,
        y_true=data.Y[test_rows, prop_index],
        y_pred=predicted,
    )
    logger.log_metrics(
        {
            f"outer/{prop}/{k}": v
            for k, v in metrics.items()
            if isinstance(v, (int, float))
        },
        step=fold,
    )
    return result


def run_nested_xgb(data: Prepared, cfg: Config, logger: RunLogger) -> NestedResult:
    """Full nested run for Track 1: every property, every outer fold."""
    started = time.perf_counter()
    logger.log_params({"search_space": XGB_SPACE, "track": "xgboost"})

    results: list[OuterFoldResult] = []
    for prop_index, prop in enumerate(PROPERTIES):
        for fold in range(data.folds.n_outer):
            result = _run_one_cell(data, cfg, prop, prop_index, fold, logger)
            results.append(result)
            print(
                f"  {prop:<6} fold {fold}  "
                f"rmse={result.metrics['rmse']:8.3f}  "
                f"rmse/sd={result.metrics['rmse_over_sd']:.3f}  "
                f"rho={result.metrics['spearman']:.3f}  "
                f"n={result.n_test:>6,}  "
                f"trials={result.n_trials} ({result.n_pruned} pruned)  "
                f"{result.seconds:.0f}s",
                flush=True,
            )

    nested = NestedResult(
        feature_name=data.feature_name,
        featurizer_version=data.featurizer_version,
        results=results,
        seconds=time.perf_counter() - started,
    )
    logger.log_dict(
        {
            "estimate": nested.estimate(),
            "cells": [
                {
                    "property": r.property,
                    "fold": r.fold,
                    "best_params": r.best_params,
                    "best_inner_score": r.best_inner_score,
                    "n_estimators_refit": r.n_estimators_refit,
                    "n_trials": r.n_trials,
                    "n_pruned": r.n_pruned,
                    "n_train": r.n_train,
                    "n_test": r.n_test,
                    "metrics": r.metrics,
                    "seconds": round(r.seconds, 1),
                }
                for r in results
            ],
        },
        "nested_xgb",
    )
    logger.log_dict(
        {f"{r.property}_fold{r.fold}": r.trials for r in results}, "optuna_trials"
    )
    return nested
